let suggestions = [
    "Army",
    "Politician",
    "Scientist",
    "Singers",
    "Social Activists",
    "Sports",
    "Teachers",
    "Writers",
    "Sam Manekshaw",
    "K. M. Cariappa",
    "Captain Vikram Batra",
    "Major Somnath Sharma",
    "Captain Manoj Kumar Pandey",
    "Captain Saurabh Kalia",
    "Captain Anuj Nair",
    "Brigadier Kuldip Singh Chandpuri",
    "Major Sandeep Unnikrishnan",
    "Albert Einstein",
    "C V Raman",
    "Isaac Newton",
    "A P J Abdul Kalam",
    "Marie Curie",
    "Srinivasa Ramanujan",
    "Stephen Hawking",
    "Homi J Bhabha",
    "Nikola Tesla",
    "SP Balasubrahmanyam",
    "David Bowie",
    "Kishore Kumar",
    "Nipsey Hussle",
    "Muhammad Rafi",
    "Tupac Shakur",
    "R D Burman",
    "the Notorious B.I.G",
    "Chester Bennington",
    "Jane Addams",
    "Vinoba Bhave",
    "Frances Perkins",
    "Baba Amte",
    "Jeannette Rankin",
    "Madhusudan Das",
    "Edith Abbott",
    "Gopabandhu Das",
    "Milkha Singh",
    "Sir Don Bradman",
    "Balbir Singh Sr",
    "Don Larsen",
    "Rajinder Goel",
    "Sam Wyche",
    "Dhyan Chand",
    "Rocky Johnson",
    "Chetan Chauhan",
    "Chanakya",
    "Helen Keller",
    "Dr Sarvepalli Radhakrishnan",
    "Anne Sullivan",
    "Savitribai Phule",
    "John Adams",
    "Pythagoras",
    "Vinoba Bhave",
    "Rabindranath Tagore",
    "Munsi Premchand",
    "Alokeranjan Dasgupta",
    "R K Narayan",
    "William Shakesphere",
    "Mahadeviverma",
    "Sugathakumari",
    "O Henry"
    
];

